### ISSUE TITLE
No Value history in HA with the last converter

### ISSUE THREAD

**Issue by seblang** [vk496/zigbee-herdsman-converters#4] opened 2022-01-05 08:40 UTC
@vk496

After correction done on lixee.js  remove **//** in line  "const {Buffer} = require('buffer');"

The result is the same :

Sensor sinsts update ok and measurement history in HA ok

![lixee](https://user-images.githubusercontent.com/11487773/148187847-453657ce-166a-4afc-91ec-c28aed87ef5d.JPG)
Sensors easf01 to easf06 + east value appear to be ok but no measurement history in HA
![lixee1](https://user-images.githubusercontent.com/11487773/148187884-c1c7e90d-803b-4a5f-970c-70bcd627866e.JPG)

Sensors are active in MQTT and no exclusion  in record (configuration.yaml)

**Comment by vk496** [comment] 2022-01-05 08:46
@seblang your links are not visible to me. If they are images, you can drag them directly here and they will be uploaded to github automatically

**Comment by seblang** [comment] 2022-01-05 08:47
@vk496 ok update done! I have learn a new fonction :-)

**Comment by vk496** [comment] 2022-01-05 09:14
thnks,

EASF01-06 reflect data change in the Z2M frontend? The problem is just communication Z2M - HA ?

BTW, could you please share with me your value from STGE?

**Comment by seblang** [comment] 2022-01-05 09:54
in z2m :
![lixee2](https://user-images.githubusercontent.com/11487773/148196589-22dace7a-f905-476a-a9d2-8aba3343c19b.JPG)

in HA :
![lixee3](https://user-images.githubusercontent.com/11487773/148196612-541f4be3-657d-4cb6-9a9a-a90dd4a6dd6e.JPG)


Other issue for me :

![lixee5](https://user-images.githubusercontent.com/11487773/148197236-70915b32-a2bd-44f1-883d-5be85ba8ff75.JPG)

SINSTS (consumption) = 0 W
My solar pannel produce = 1296 W
If I stop my solar production  consumption = 500w

So I have to see in SINSTI (after solar restart) the difference = 796w injection

No?

**Comment by vk496** [comment] 2022-01-05 10:02
SINSTS and SINSTI are reportable values, so I had to check if subscription is done correctly. Could you check what do you have in reports?

Btw, your labels from LiXee clusters are null (NGTF, LTARF, DATE, ....). Could you please check which version of zigbee-herdsman is using your Z2M?

**Comment by seblang** [comment] 2022-01-05 10:06
How can I check the zigbee-herdsman ? 

After restart i have an update but the value stay stable again after
![lixee5](https://user-images.githubusercontent.com/11487773/148199590-cc5e9f62-ac59-4088-93f5-e436cc9b62f2.JPG)
.

**Comment by vk496** [comment] 2022-01-05 10:31
Hi,

For now I just did the hack to read periodically all values, so you could check if is working better for you. In any case, I definitely should fix the reportings of the device, since is better to let the firmware report when values change instead of polling all each time.

Regarding to zigbee-hersman, it should appear in the logs. Maybe you had to enable debug in the Z2M configuration (https://www.zigbee2mqtt.io/guide/usage/debug.html)

Note: I switched from Wh to kWh, let me know if is working well

**Comment by seblang** [comment] 2022-01-05 10:46
Zigbee2MQTT:info  2022-01-05 11:41:08: Starting Zigbee2MQTT version 1.22.2-dev (commit #4f887a1)
Zigbee2MQTT:info  2022-01-05 11:41:08: Starting zigbee-herdsman (0.13.190)


ok for the change in KWH

![lixee6](https://user-images.githubusercontent.com/11487773/148204536-51ba513c-315f-4810-800a-bf16a9484a78.JPG)

I am restarting HA to check the new lixee.js file

I come back after a few moment.....of test

**Comment by vk496** [comment] 2022-01-05 12:30
Weird.... I don't understand why EAST and EASF01,02 still reports as Wh and the rest as kWh. Doesn't make sense. They should all do exactly the same.

Also, zigbee-herdsman seems to be at 0.13.190, so lixee clusters should work for you, but you still have null on that labels. Do you have any kind of errors in the logs?

**Comment by seblang** [comment] 2022-01-05 13:20
hello no error in logs !

Value are in KWH after a restart
![lixee6](https://user-images.githubusercontent.com/11487773/148224196-c888edcb-2f56-4fb0-ba4f-45ae1289886a.JPG)

**Comment by seblang** [comment] 2022-01-06 10:15
Hi @vk496 

**It's working fine for me with the last change :**

for (const e of getCurrentConfig(device, options)) {

**I will do a trial again with old parameter :**

for (const e of getCurrentConfig(device, options).filter((e) => !e.reportable)) {

I have just to replace this line in my lixee.js or you have wording change to propose?

**Comment by vk496** [comment] 2022-01-06 10:24
That means that reporting of different labels doesn't work for you. I had to look why is happening, but for now we can leave it like this

**Comment by seblang** [comment] 2022-01-06 10:34
Yes we can leave it like this, just the DB get bigger quickly despite I have exclude most of entities in record (configuration.YAML)

**Comment by seblang** [comment] 2022-01-11 13:22
Hi @vk496 

Since this morning I have again an issue! no record again! If I check in Z2m log in debug version it appear that some information are received but it's alwais the same value !

![lixee8](https://user-images.githubusercontent.com/11487773/148949878-6daf0e2b-e276-4589-aced-c0aba394ca9f.JPG)

My curve are flat again!
If Z2M receive info without any error message can I conclude that it's my ZLINKY module the issue?

**Comment by vk496** [comment] 2022-01-11 14:35
@seblang when do you have multiple messages, it doesn't mean that data is received. It could be just chnages in linkquality, which creates a new MQTT message.

In any case, you could try to use the develop console to manually read values and check if is working properly

**Comment by seblang** [comment] 2022-01-12 11:36
hi @vk496 

Today again the sensor are staying againg!

I have done the test in dev console :
Value (zero) ok (linky value) and no communication issue with Zlinky

![lixee10](https://user-images.githubusercontent.com/11487773/149132952-00ef94f9-ed53-4a77-ae6f-5738eb4add31.JPG)

But If I check in received message and in périphérique expose

![lixee12](https://user-images.githubusercontent.com/11487773/149133128-8632bb50-84d9-44ff-af0b-c190bade2cb4.JPG)
![lixee13](https://user-images.githubusercontent.com/11487773/149133138-8fe7eeeb-4315-418b-9838-e3eb8ae82069.JPG)


I have changed nothing! What is the issue? The mqtt base?

**Comment by seblang** [comment] 2022-01-12 12:27
@vk496 

More info, I produce electricity and what I see is when I produce more than the consumption the value remains at the last level!
If my consumption is higher I can see the evolution (new value) but immediately after my consumption is lower than what I produce the sensor stay again blocked!

The Zlinky sends the info (goes down to zero  according feedback from dev console) but the Z2M does not zero the sensor, there is one last value left!

Strange without any change! (just last Ha update)

![lixee14](https://user-images.githubusercontent.com/11487773/149140104-e75875df-1039-4f8c-8bf4-712f41ee0c57.JPG)
![lixee15](https://user-images.githubusercontent.com/11487773/149140111-b4482919-5570-4a59-81f8-fb2873bfe442.JPG)
![lixee16](https://user-images.githubusercontent.com/11487773/149140119-16637924-cd39-4f03-8a18-5c060e2b1d57.JPG)

**Comment by seblang** [comment] 2022-01-13 12:29
Hi @vk496 
today it's the same, when I send a request to Zlinky through the dev console I have the right information (same as on ly linky), but the sensor HA and in Z2M console is not updated.

Any idea to solve this?
tahnk you in advance

**Comment by vk496** [comment] 2022-01-13 12:58
@seblang I'm not sure how to solve your issue. I think we need to confirm with more people if is something specific to you or happens to more people.

Anyway, the integration is ready to merge. Once it will be in Z2M dev out of the box, more people could validate the issue.

**Comment by seblang** [comment] 2022-01-15 11:16
@vk496 

Do you know when it will be merged?

Other point, if I want more precision on my sensor  (XXX.XXX KW instead of XXXKW) what is the necessary change in lixee.js ?
![Screenshot 2022-01-15 12 10 49](https://user-images.githubusercontent.com/11487773/149619732-40c5891b-7f21-4f24-9f61-9fc21f7171bb.png)

**Comment by seblang** [comment] 2022-01-16 13:12
@vk496 

if I want more precision on my sensor (XXX.XXX KW instead of XXXKW) what is the necessary change in lixee.js ?

**Comment by vk496** [comment] 2022-01-17 13:12
@seblang I would prefer that you open a new issue for each new problem/request that you want to comunicate, so we don't flood this issue with stuff that are not related. That help me to track all issues/problems in the integration and don't forget anything.

Regarding your request, I will try to implement it

**Comment by vk496** [comment] 2022-02-15 18:00
@seblang The problem could be related with the device HW problem. I already saw mentioning this somewhere (I think they send it back to the store to get a new one). Please take a look in the https://github.com/fairecasoimeme/Zlinky_TIC/issues , I think is mentioned somewhere there.

Feel free to reopen the issue if you need it

**Closed as completed by vk496** 2022-02-15 18:00 UTC
