### ISSUE TITLE
Too many messages being send on MQTT

### ISSUE THREAD

**Issue by antoinelibert** [vk496/zigbee-herdsman-converters#15] opened 2022-02-05 19:00 UTC
Hello,

Just installed the latest dev version of zigbee2mqtt with Lixee module included. I have noticed a lot of messages being sent on the broker with the same identical payload. Currently, the module is sending multiple messages per second to the broker. 

Zigbee2MQTT version
1.23.0-dev commit: [b5e8566](https://github.com/Koenkk/zigbee2mqtt/commit/b5e8566)
Coordinator type
ConBee2/RaspBee2
Coordinator revision
0x26720700
Frontend version
0.6.71

ZLinky_TIC Router v4.0

![image](https://user-images.githubusercontent.com/10107072/152655091-67336301-aa91-4f3e-a446-c640d3a7bb42.png)
![image](https://user-images.githubusercontent.com/10107072/152655113-1eeac5cf-ded9-4b7a-a1c9-8d20fb2d46f2.png)

**Comment by antoinelibert** [comment] 2022-02-05 19:16
I have set `debounce: 2` to the device and it lowered the number of messages. Is it supposed to happen with the poll_interval setting set to 60?

**Comment by antoinelibert** [comment] 2022-02-06 15:29
I have managed to reduce the number of messages on the broker by customizing/removing Clusters that I don't need (I only need 5 values). Also I have modified the integration so that all attributes reporting are being set to a `Min rep interval` of 5 instead of 0.

I'm suspecting that the Linky module is sending a unique report for each changed value and with the high numbers of clusters available for me (standard mode, base contract, no production), it's flooding the network. I would suggest that it might be better to offer some kind of configuration to enable/disable each attribute instead and leave the choice to the user.

Not related I think but I got also a very weird bug, my module `zigbeeModel` attribute changed to `'ZLinky_TIC\u0000'` (with the unprintable char \u0000) after multiple resets/pairing (I was experimenting). So I had to add a second model name for zigbee2mqtt to recognize the module.

**Comment by vk496** [comment] 2022-02-15 17:56
Hello,

The flood is caused by zlinky for reporting attributes. Currently, I set a minimum report time of 60s, so it should not flood anymore. You can manually modify that stuff in the Z2M frontend.

Regarding to the null char in the model... do you still have the problem?

**Comment by antoinelibert** [comment] 2022-02-15 18:11
Hello,

Yeah I still have the model issue:

![image](https://user-images.githubusercontent.com/10107072/154122895-0855eff1-547d-4ece-9d31-cf804bec44a3.png)

**Comment by vk496** [comment] 2022-02-15 18:14
@Koenkk there is some elegant way to handle this?

**Comment by antoinelibert** [comment] 2022-02-15 18:20
You could do `zigbeeModel: ['ZLinky_TIC', 'ZLinky_TIC\u0000']`? Not great but works fine for me.

**Comment by vk496** [comment] 2022-02-15 18:26
Oh, that's cool. I thought I had to duplicate a lot of stuff... But that is clean and tiny :)

**Comment by Koenkk** [comment] 2022-02-15 18:33
> @Koenkk there is some elegant way to handle this?

Increasing the min reporting way is the best way.

**Comment by vk496** [comment] 2022-02-15 18:38
ok. Then I can close this issue

**Closed as completed by vk496** 2022-02-15 18:38 UTC
